# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NvdbQgisPlugin
                                 A QGIS plugin
 Fetch data from nvdb and visualize it in QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-16
        copyright            : (C) 2021 by Erlend Ellefsen & Robin Ellingsen
        email                : ekbe_97@hotmail.no
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """
    Load NvdbQgisPlugin class from file NvdbQgisPlugin.
    Kjører start.py
    """


    script_dir = os.path.dirname(__file__)
    rel_path = 'start.py'
    path = os.path.join(script_dir, rel_path)
    exec(open(path.encode('utf-8')).read())
    from .nvdb_qgis_plugin import NvdbQgisPlugin
    return NvdbQgisPlugin(iface)
